apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-app
  namespace: dev-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
      - name: youtube-container
        image: docker push 295428651620.dkr.ecr.us-east-1.amazonaws.com/youtube:tagversion
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-service
  namespace: dev-env
spec:
  type: LoadBalancer
  selector:
    app: youtube
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
